language: node_js
services:
    - docker
install:
    - docker --version
    - docker-compose --version
test:
    - npm test
env:
    - NODE_ENV=test
    - JWT_SECRET=dummysecret
    - MONGO_URI=mongodb://db:27017/testdb