export const dummy = [
  {
    _id: '507f1f77bcf86cd799439011',
    firstName: 'Steven',
    lastName: 'Bianchi',
    jobTitle: 'VP People',
    startDate: '16/09/2019',
    department: 'People',
    location: 'GB',
    manager: 'Abakar Saidov',
    email: 'steven.bianchi@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    _id: '507f1f77bcf86cd799439012',
    firstName: 'Thomas',
    lastName: 'Kostrzewski',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'thomas.kostrzewski@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    _id: '507f1f77bcf86cd799439013',
    firstName: 'Antonio',
    lastName: 'Gargaro',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'antonio.gargaro@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    _id: '507f1f77bcf86cd799439014',
    firstName: 'Lyndsey',
    lastName: 'Scott',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'lyndsey.scott@beamery.com',
    gender: 'Female',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    _id: '507f1f77bcf86cd799439015',
    firstName: 'João',
    lastName: 'Viana',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'joao.viana@beamery.com',
    gender: 'Male',
    stage: 'registered',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
];
