const ObjectID = require("mongodb").ObjectID;
module.exports = [
    {
        _id: ObjectID("507f1f77bcf86cd799439011"),
        firstName: "Steven",
        lastName: "Bianchi",
        jobTitle: "VP People",
        startDate: "16/09/2019",
        department: "People",
        location: "GB",
        manager: "Abakar Saidov",
        email: "steven.bianchi@beamery.com",
        gender: "Male",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439012"),
        firstName: "Thomas",
        lastName: "Kostrzewski",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "thomas.kostrzewski@beamery.com",
        gender: "Male",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439013"),
        firstName: "Antonio",
        lastName: "Gargaro",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "antonio.gargaro@beamery.com",
        gender: "Male",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439014"),
        firstName: "Lyndsey",
        lastName: "Scott",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "lyndsey.scott@beamery.com",
        gender: "Female",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439015"),
        firstName: "João",
        lastName: "Viana",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "joao.viana@beamery.com",
        gender: "Male",
        stage: "registered",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439016"),
        firstName: "Tom",
        lastName: "Galligan",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "tom.galligan@beamery.com",
        gender: "Male",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439017"),
        firstName: "Martha",
        lastName: "Lambert",
        jobTitle: "Graduate Software Engineer",
        startDate: "09/09/2019",
        department: "Engineering",
        location: "GB",
        manager: "Andrew Celi",
        email: "martha.lambert@beamery.com",
        gender: "Female",
        stage: "ramping_up",
        employmentStatus: "",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439018"),
        firstName: "Harshada",
        lastName: "Shimpi",
        jobTitle: "QA Engineer",
        startDate: "19/08/2019",
        department: "Engineering",
        location: "GB",
        manager: "Gideon Gluckman",
        email: "harshada.shimpi@beamery.com",
        gender: "Female",
        stage: "ramping_up",
        employmentStatus: "",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439019"),
        firstName: "Jeff",
        lastName: "Lu",
        jobTitle: "Head of Talent Acquisition",
        startDate: "05/08/2019",
        department: "People",
        location: "GB",
        manager: "Steven Bianchi",
        email: "jeff.lu@beamery.com",
        gender: "Male",
        stage: "ramping_up",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439023"),
        firstName: "Rachel",
        lastName: "Skelton",
        jobTitle: "HR and Talent manager",
        startDate: "02/07/2019",
        department: "People",
        location: "GB",
        manager: "Steven Bianchi",
        email: "rachel.skelton@beamery.com",
        gender: "Female",
        stage: "registered",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439033"),
        firstName: "Takveen",
        lastName: "Bashir",
        jobTitle: "Senior Technical Recruiter",
        startDate: "05/11/2018",
        department: "People",
        location: "GB",
        manager: "Jeff Lu",
        email: "takveen@beamery.com",
        gender: "Female",
        stage: "registered",
        employmentStatus: "",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439043"),
        firstName: "Milo",
        lastName: "Abel",
        jobTitle: "Recruiting Programs & Operations Associate",
        startDate: "16/07/2018",
        department: "People",
        location: "GB",
        manager: "Murad Saidov",
        email: "milo@beamery.com",
        gender: "Male",
        stage: "registered",
        employmentStatus: "",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439053"),
        firstName: "Minesh",
        lastName: "Shah",
        jobTitle: "Junior Software Engineer",
        startDate: "26/02/2018",
        department: "Engineering",
        location: "GB",
        manager: "Daniel octavian Stanciu",
        email: "minesh.shah@beamery.com",
        gender: "Male",
        stage: "registered",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439063"),
        firstName: "Adam",
        lastName: "Rabinovitch",
        jobTitle: "Lead Technical Recruiter",
        startDate: "01/02/2018",
        department: "People",
        location: "GB",
        manager: "Jeff Lu",
        email: "adam@beamery.com",
        gender: "Male",
        stage: "registered",
        employmentStatus: "Permanent- FT",
        office: "London"
    },
    {
        _id: ObjectID("507f1f77bcf86cd799439073"),
        firstName: "Natasha",
        lastName: "Lees",
        jobTitle: "Commercial Recruiting Lead",
        startDate: "18/12/2017",
        department: "People",
        location: "US",
        manager: "Jeff Lu",
        email: "natasha@beamery.com",
        gender: "Female",
        stage: "registered",
        employmentStatus: "Permanent- FT",
        office: "ATX"
    }
];
