const ObjectID = require('mongodb').ObjectID;

module.exports = [
  {
    id: ObjectID('507f1f77bcf86cd799439012'),
    slackId: 'UL82XRQCE',
    firstName: 'Thomas',
    lastName: 'Kostrzewski',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'thomas.kostrzewski@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    id: ObjectID('507f1f77bcf86cd799439013'),
    slackId: 'UL983SCPL',
    firstName: 'Antonio',
    lastName: 'Gargaro',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'antonio.gargaro@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    id: ObjectID('507f1f77bcf86cd799439014'),
    slackId: 'UL59YGZEH',
    firstName: 'Lyndsey',
    lastName: 'Scott',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'lyndsey.scott@beamery.com',
    gender: 'Female',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    id: ObjectID('507f1f77bcf86cd799439015'),
    slackId: 'UMM7XP8DR',
    firstName: 'João',
    lastName: 'Viana',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'joao.viana@beamery.com',
    gender: 'Male',
    stage: 'registered',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    id: ObjectID('507f1f77bcf86cd799439016'),
    slackId: 'UMXURMH0V',
    firstName: 'Tom',
    lastName: 'Galligan',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'tom.galligan@beamery.com',
    gender: 'Male',
    stage: 'ramping_up',
    employmentStatus: 'Permanent- FT',
    office: 'London',
  },
  {
    id: ObjectID('507f1f77bcf86cd799439017'),
    slackId: 'UKTQ57P0T',
    firstName: 'Martha',
    lastName: 'Lambert',
    jobTitle: 'Graduate Software Engineer',
    startDate: '09/09/2019',
    department: 'Engineering',
    location: 'GB',
    manager: 'Andrew Celi',
    email: 'martha.lambert@beamery.com',
    gender: 'Female',
    stage: 'ramping_up',
    employmentStatus: '',
    office: 'London',
  },
];
